# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ refactor ]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build jlinkZip
    - uses: actions/upload-artifact@v2
      with:
        name: JarFile-${{ matrix.os }}
        path: build/libs
    - uses: actions/upload-artifact@v2
      with:
        name: NativeBuild-${{ matrix.os }}
        path: build/image.zip